####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, TAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
#trace_geography:
  #TAZ: 21
  #TRACT: 10200

  
# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : hh_pums_2019_5YR.csv
    index_col: hh_id
    rename_columns:
      # not sure what SERIALNO is, but it is not unique
      SERIALNO: hh_id
      #hhnum: hh_id
      HH: num_hh
    drop_columns:
      - ESR
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : person_pums_2019_5YR.csv
    rename_columns:
      SERIALNO: hh_id
      #hhnum: hh_id
      SPORDER: per_num
    # drop unused mixed type fields to avoid PyTables pipeline performance issues
    # (PyTables will pickle object types that it cannot map directly to c-types)
    drop_columns:
      - indp02
      - naicsp02
      - occp02
      - socp00
      - occp10
      - socp10
      - indp07
      - naicsp07
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
    column_map:
      TAZ: TAZ
  - tablename: TAZ_control_data
    filename : 2040_LandUse_update_06_07_2022.csv #updated TAZ 208757
    rename_columns:
      ID: TAZ
  - tablename: REGION_control_data
    #filename : control_totals_meta.csv
    filename : region_control_2040.csv
    rename_columns:
      HH: num_hh


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: HH


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_TAZ
    - summary_TAZ_PUMA
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - HHNP
      - HHEMPCAT
      - HHINCPADJ
  persons:
    filename: synthetic_persons.csv
    columns:
      - EMP
      - PINCPADJ


# Model steps for base mode
# ------------------------------------------------------------------
models:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    #- sub_balancing.geography=TRACT
    - sub_balancing.geography=TAZ
    - expand_households
    - write_data_dictionary
    - summarize
    - write_tables
    - write_synthetic_population

resume_after:
